networks:
  microservice_network:
    driver: bridge


services:

  user_mysql:
    image: mariadb:10.5.8
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    env_file:
      - .env.production
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - microservice_network

  phpmyadmin:
    depends_on:
      - user_mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8086:80'
    env_file:
      - .env.production
    environment:
      - PMA_HOST=${DB_HOST}
      - PHP_ENABLE_XDEBUG=0
      - UPLOAD_LIMIT=300M
    networks:
      - microservice_network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - microservice_network

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    env_file:
      - .env.production
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
        - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
        - ./docker/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - microservice_network

  gateway:
    build:
      context: .
      dockerfile: /apps/gateway/Dockerfile.production
      target: production
    command: ["pm2-runtime", "start", "dist/apps/gateway/main.js"]
    env_file:
      - .env.production
    depends_on:
      - user_mysql
      - redis
      - rabbitmq
      - users
      - notifications
    volumes:
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - microservice_network
  
  users:
    build:
      context: .
      dockerfile: /apps/users/Dockerfile.production
      target: production
    command: ["pm2-runtime", "start", "dist/apps/users/main.js"]
    env_file:
      - .env.production
    # environment:
    #   - DB_URL="mysql://root:microservice@user_mysql:3306/microservice_user_app?schema=public"
    depends_on:
      - user_mysql
      - redis
      - rabbitmq
      - notifications
    volumes:
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
    networks:
      - microservice_network
  
  notifications:
    build:
      context: .
      dockerfile: /apps/notifications/Dockerfile.production
      target: production
    command: ["pm2-runtime", "start", "dist/apps/notifications/main.js"]
    env_file:
      - .env.production
    depends_on:
      - user_mysql
      - redis
      - rabbitmq
    volumes:
      - /usr/src/app/node_modules
    ports:
      - '3002:3002'
    networks:
      - microservice_network