FROM node:22-alpine AS development

WORKDIR /usr/src/app

# Copy the root package.json and package-lock.json
COPY package*.json ./

RUN npm install

COPY nest-cli.json ./
COPY tsconfig*.json ./

COPY apps/notifications ./apps/notifications
COPY libs ./libs

# Verify that package.json is copied
RUN ls -la /usr/src/app && cat /usr/src/app/package.json


RUN npm run build notifications

EXPOSE 3002

CMD npm run start:dev notifications