networks:
  microservice_network:


services:

  user_mysql:
    image: mariadb:10.5.8
    container_name: microservice_user_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - microservice_network

  phpmyadmin:
    container_name: microservice_phpmyadmin
    depends_on:
      - user_mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8086:80'
    env_file:
      - .env
    networks:
      - microservice_network

  redis:
    image: redis:alpine
    container_name: microservice_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - microservice_network

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: microservice_rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
        - microservice_network